In [54]:
import pandas as pd
import numpy as np
import seaborn as sns
import string
import re
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [23]:
a = pd.read_csv(r'C:/Users/LALITH RAJ R/AI-Driven_Governance_Platform_For_Citizen_Services/Pre_Processing/data.csv')

In [24]:
df = a
df

,complaint_text,officer_behaviour,amount
0,"Forced ah INR 25,000 vanginaanga Ration PDS of...",Bad,3000
1,The inspector at BESCOM handled everything wit...,Good,0
2,staff member ne Police station mein sab sahi s...,Good,0
3,Trade licence office ke desk officer ne broker...,Good,0
4,Cash demanded,Bad,5000
...,...,...,...
8495,"INR 2,000 ki demand khullam khulla Trade licen...",Bad,1500
8496,"supervisor ne seedha INR 2,000 magitla Educati...",Bad,500
8497,Health department head clerk deserves apprecia...,Good,0
8498,"Broker illama velai achu Water board la, head ...",Good,0
8499,"Ek rupaya nahi dena tha par INR 4,000 Educatio...",Bad,40000

In [25]:
df.iloc[:, 0][1]

'The inspector at BESCOM handled everything without asking for a single rupee'

In [26]:
df.isnull().sum()

complaint_text       0
officer_behaviour    0
amount               0
dtype: int64

In [27]:
# Here we have to build a pipeline 
"""
lower case 
html tags
punctuations 
urls
chat word teratement(u -> you)
spelling correction 
remve stop words
"""

'\nlower case \nhtml tags\npunctuations \nurls\nchat word teratement(u -> you)\nspelling correction \nremve stop words\n'

In [ ]:
#!pip install scikit-learn

<h2>Lower case</h2>

In [29]:
def lower_casing(val):
    return val.str.lower()

In [30]:
df.iloc[:,0] = lower_casing(df.iloc[:,0])

<h2>HTML Taging</h2>

In [31]:
import re
def html_taging(b):
    li = []
    for i in range(len(b)):
        li.append(re.sub('<.*?>', "", b[i]))
    return li

In [ ]:
#df.iloc[:,0][1] = 'the inspector <b> at bescom handled </b> everything without asking for a single rupee'
#df.iloc[:,0][1] = 'the inspector <b> at bescom handled everything </b> without asking for a single rupee'
df.at[1, 'complaint_text'] = "the inspector <b> at bescom handled everything </b> without asking for a single rupee"
df

,complaint_text,officer_behaviour,amount
0,"forced ah inr 25,000 vanginaanga ration pds of...",Bad,3000
1,the inspector <b> at bescom handled everything...,Good,0
2,staff member ne police station mein sab sahi s...,Good,0
3,trade licence office ke desk officer ne broker...,Good,0
4,cash demanded,Bad,5000
...,...,...,...
8495,"inr 2,000 ki demand khullam khulla trade licen...",Bad,1500
8496,"supervisor ne seedha inr 2,000 magitla educati...",Bad,500
8497,health department head clerk deserves apprecia...,Good,0
8498,"broker illama velai achu water board la, head ...",Good,0
8499,"ek rupaya nahi dena tha par inr 4,000 educatio...",Bad,40000

In [52]:
# df.iloc[:,0] = html_taging(df.iloc[:,0])
df.iloc[:,0] = html_taging(df.iloc[:,0])

<h2>urls</h2>

In [53]:
def urls(b):
    li = []
    for i in range(len(b)):
        li.append(re.sub(r'http\S+|www\S+', '', b[i]))
    return li
df.iloc[:,0] = urls(df.iloc[:,0])

<h2>punctuations </h2>

In [55]:
def punctiations(b):
    li = []
    for i in range(len(b)):
        li.append(re.sub(r'''[!"#$%&'()*+,\-./:;<=>?@\[\\\]^_`{|}~]''', '', b[i]))
    return li
df.iloc[:,0] = punctiations(df.iloc[:,0])

<h1>chat word teratement</h1>

In [58]:
chat_words = {
    # Common chat abbreviations
    "luv": 'love',
    "u": "you",
    "ur": "your",
    "r": "are",
    "bt": "but",
    "bcz": "because",
    "bcz": "because",
    "coz": "because",
    "pls": "please",
    "plz": "please",
    "thx": "thanks",
    "tnx": "thanks",
    "msg": "message",
    "govt": "government",
    "dept": "department",
    "doc": "document",
    "docs": "documents",
    "app": "application",
    "appt": "appointment",
    "info": "information",

    # Corruption-related shorthand
    "hafta": "bribe",
    "rishwat": "bribe",
    "undertable": "under the table payment",
    "pct": "percentage commission",
    "commsn": "commission",
    "comm": "commission",
    "favr": "favor",
    "kickback": "illegal commission",

    # Office abbreviations
    "bescom": "bangalore electricity supply company",
    "bbmp": "bruhat bengaluru mahanagara palike",
    "pdo": "panchayat development officer",
    "dc": "district commissioner",
    "ac": "assistant commissioner",
    "tahsildar": "tahsildar officer",
    "rd": "revenue department",
    "pwd": "public works department",

    # Complaint language
    "wrk": "work",
    "emp": "employee",
    "offcr": "officer",
    "insp": "inspector",
    "supdt": "superintendent",
    "mgr": "manager",
    "req": "request",
    "apprv": "approve",
    "rejct": "reject",
    "pendng": "pending",
    "dlay": "delay",
    "vrfy": "verify",

    # Sentiment words
    "gr8": "great",
    "gud": "good",
    "vry": "very",
    "bad": "bad",
    "worst": "worst",
    "awsm": "awesome",
    "frndly": "friendly",
    "hlpful": "helpful",
    "unhlpful": "unhelpful",
    "corpt": "corrupt",
    "honst": "honest",

    # SMS style
    "b4": "before",
    "2day": "today",
    "2moro": "tomorrow",
    "tmrw": "tomorrow",
    "4": "for",
    "2": "to",
    "w8": "wait",
    "msgd": "messaged",
    "cntct": "contact",
    "recvd": "received",
    "submtd": "submitted"
}

In [59]:
def word_treatement(text):
    words = text.split()                       
    cleaned = [chat_words.get(w, w) for w in words]    
    return ' '.join(cleaned)                            
def chat_word_tratement(b):
    for i in range(len(b)):
        word_treatement(b[i])
    
text = "omg i luv dis movie bt it ws 2 lng"
word_treatement(text)

'omg i love dis movie but it ws to lng'